---
- name: Check healthcheck endpoint
  uri:
    url: "http://{{ healthcheck_fqdn }}:{{ healthcheck_port }}{{ healthcheck_path }}"
    method: GET
  register: health_check
  ignore_errors: no

- name: Display healthcheck results
  debug:
    msg:
      - "Host: {{ inventory_hostname }}"
      - "Healthcheck endpoint: http://{{ healthcheck_fqdn }}:{{ healthcheck_port }}{{ healthcheck_path }}"
      - "Status: {{ health_check.status | default('N/A') }}"
      - "Response: {{ health_check.content | default('N/A') | truncate(100) }}"

- name: Check metrics endpoint
  uri:
    url: "http://{{ internal_host_fqdn }}:{{ metrics_port }}{{ metrics_path }}"
    method: GET
  register: metrics_check
  ignore_errors: no

- name: Display metrics check results
  debug:
    msg:
      - "Host: {{ inventory_hostname }}"
      - "Metrics endpoint: http://{{ internal_host_fqdn }}:{{ metrics_port }}{{ metrics_path }}"
      - "Status: {{ metrics_check.status | default('N/A') }}"
      - "Response: {{ metrics_check.content | default('N/A') | truncate(100) }}"
