---
- name: Stop js-ceramic-4 node
  ansible.builtin.systemd:
    name: js-ceramic
    state: stopped
  when: inventory_hostname == 'gitcoin-js-ceramic-4.3boxlabs.com'

- name: Stop go-ipfs-2 node
  ansible.builtin.systemd:
    name: go-ipfs
    state: stopped
  when: inventory_hostname == 'gitcoin-go-ipfs-2.3boxlabs.com'

- name: Get latest Ceramic snapshot on remote machine
  ansible.builtin.shell:
    cmd: ssh gitcoin-js-ceramic-3.3boxlabs.com -i ~/.ssh/google_compute_engine "zfs list -H -t snapshot -o name ceramiconepool/data-store | sort | tail -n 1"
  when: inventory_hostname == 'gitcoin-js-ceramic-4.3boxlabs.com'
  register: remote_latest_snapshot
  changed_when: false
  delegate_to: localhost

- name: Transfer latest ZFS snapshot
  ansible.builtin.shell:
    cmd: |
      ssh gitcoin-js-ceramic-3.3boxlabs.com -i ~/.ssh/google_compute_engine "zfs send -i ceramiconepool/data-store@initial {{ remote_latest_snapshot.stdout }}" | \
      zfs receive -F ceramiconepool/data-store
  when: inventory_hostname == 'gitcoin-js-ceramic-4.3boxlabs.com'
  register: zfs_transfer_result
  failed_when: zfs_transfer_result.rc != 0

- name: Get current timestamp
  ansible.builtin.set_fact:
    timestamp: "{{ ansible_date_time.iso8601_basic_short }}"
  when: inventory_hostname == 'gitcoin-go-ipfs-2.3boxlabs.com'

- name: Backup IPFS config file with timestamp
  ansible.builtin.copy:
    src: "{{ data_store_mount_path }}/ipfs-data/config"
    dest: "/home/{{ ansible_user }}/ipfs_config_backup_{{ timestamp }}"
    remote_src: yes
  when: inventory_hostname == 'gitcoin-go-ipfs-2.3boxlabs.com'

- name: Get latest snapshot on remote machine
  ansible.builtin.shell:
    cmd: ssh gitcoin-go-ipfs-1.3boxlabs.com -i ~/.ssh/google_compute_engine "zfs list -H -t snapshot -o name ipfspool/data-store | sort | tail -n 1"
  when: inventory_hostname == 'gitcoin-go-ipfs-2.3boxlabs.com'
  register: remote_latest_snapshot
  changed_when: false
  delegate_to: localhost

- name: Transfer latest ZFS snapshot
  ansible.builtin.shell:
    cmd: |
      ssh gitcoin-go-ipfs-1.3boxlabs.com -i ~/.ssh/google_compute_engine "zfs send -i ipfspool/data-store@initial {{ remote_latest_snapshot.stdout }}" | \
      zfs receive -F ipfspool/data-store
  when: inventory_hostname == 'gitcoin-go-ipfs-2.3boxlabs.com'
  register: zfs_transfer_result
  failed_when: zfs_transfer_result.rc != 0

- name: Restore IPFS config file
  ansible.builtin.copy:
    src: "/home/{{ ansible_user }}/ipfs_config_backup_{{ timestamp }}"
    dest: "{{ data_store_mount_path }}/ipfs-data/config"
    remote_src: yes
  when: inventory_hostname == 'gitcoin-go-ipfs-2.3boxlabs.com'

- name: Create symlink to latest config backup
  ansible.builtin.file:
    src: "/home/{{ ansible_user }}/ipfs_config_backup_{{ timestamp }}"
    dest: "/home/{{ ansible_user }}/ipfs_config_backup_latest"
    state: link
  when: inventory_hostname == 'gitcoin-go-ipfs-2.3boxlabs.com'

- name: Start go-ipfs-2 node
  ansible.builtin.systemd:
    name: go-ipfs
    state: started
  when: inventory_hostname == 'gitcoin-go-ipfs-2.3boxlabs.com'

- name: Start js-ceramic-4 node
  ansible.builtin.systemd:
    name: js-ceramic
    state: started
  when: inventory_hostname == 'gitcoin-js-ceramic-4.3boxlabs.com'
