---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: node-heapsnapshot
spec:
  schedule: "0 */4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: node-heapsnapshot
              image: node-heapsnapshot/node-heapsnapshot
              env:
                - name: REMOTE_HOST
                  value: ceramic-debug
                - name: REMOTE_PORT
                  value: "9229"
                - name: HEAP_PATH
                  value: /tmp
                - name: BUCKET_NAME
                  value: benchmarking-ceramic--ceramic-heap-snapshot
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: ceramic-heap-snapshot
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: ceramic-heap-snapshot
                      key: AWS_SECRET_ACCESS_KEY
              resources:
                limits:
                  cpu: 1024m
                  memory: 1Gi
                requests:
                  cpu: 1024m
                  memory: 1Gi
          restartPolicy: Never
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1