---

- name: Setup Node
  become: yes
  become_flags: --login
  become_user: ceramic
  block:
    - name: Install nvm
      ansible.builtin.shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.nvm/nvm.sh"

    - name: Setup .bashrc
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        line: source ~/.nvm/nvm.sh # This will make sure Node is on the user's PATH
        create: yes

    - name: Install node
      ansible.builtin.shell: |
        source ~/.nvm/nvm.sh && echo $PATH && nvm install {{item}}
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.nvm/versions/node/{{item}}"
      loop:
        - "{{ ceramic_node_version }}"
      register: install_node_version

- name: Setup Ceramic
  become: yes
  become_flags: --login
  become_user: ceramic
  block:
    - name: Install ceramic
      ansible.builtin.shell: |
        source ~/.nvm/nvm.sh && npm install -g @composedb/cli@{{composedb_cli_version}} @ceramicnetwork/cli@{{js_ceramic_version}}
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.nvm/versions/node/{{item}}/bin/ceramic"
      loop:
        - "{{ceramic_node_version}}"
      register: install_ceramic_version

    - name: Template ceramic daemon.config
      ansible.builtin.template:
        src: "ceramic-daemon-config.json.j2"
        dest: "{{ js_ceramic_data_mount_path }}/daemon.config.json"
      register: ceramic_daemon_config

- name: "Setup Ceramic systemd unit"
  become: yes
  block:
    - name: "Template ceramic systemd unit"
      ansible.builtin.template:
        src: "js-ceramic.service.j2"
        dest: "/etc/systemd/system/js-ceramic.service"
      register: ceramic_systemd_unit

    - name: "Start and enable ceramic systemd unit"
      ansible.builtin.systemd:
        name: "js-ceramic"
        state: "started"
        enabled: true
        daemon_reload: true

- name: "Start and enable ceramic systemd unit"
  ansible.builtin.systemd:
    name: "js-ceramic"
    state: "restarted"
    enabled: true
    daemon_reload: true
  when: ceramic_daemon_config.changed
