---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: ipfs
spec:
  template:
    metadata:
      labels:
        app: ipfs
    spec:
      containers:
        - name: ipfs
          resources:
            requests:
              cpu: "3"
              ephemeral-storage: 1Gi
              memory: 4096Mi
            limits:
              cpu: "3"
              ephemeral-storage: 1Gi
              memory: 8192Mi