---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: composedb
spec:
  template:
    metadata:
      labels:
        app: composedb
    spec:
      containers:
        - name: composedb
          resources:
            requests:
              cpu: "3"
              ephemeral-storage: 1Gi
              memory: 4096Mi
            limits:
              cpu: "3"
              ephemeral-storage: 1Gi
              memory: 8192Mi