---
- hosts: all
  become: true
  roles:
    - name: ceramic-prep
      import_role:
        name: ceramic-prep
      tags: ceramic-prep
    - name: zfs
      import_role:
        name: zfs
      tags: zfs
    - name: grafana-alloy
      import_role:
        name: grafana-alloy
      tags: grafana-alloy

- hosts: rust_ceramic
  become: true
  roles:
    - name: rust-ceramic
      import_role:
        name: rust-ceramic
      tags: rust-ceramic

- hosts: go_ipfs
  become: true
  roles:
    - name: docker
      import_role:
        name: docker
      tags: docker
    - name: go-ipfs
      import_role:
        name: go-ipfs
      tags: go-ipfs

- hosts: js_ceramic
  become: true
  roles:
    - name: js-ceramic
      import_role:
        name: js-ceramic
      tags: js-ceramic
    - name: caddy
      import_role:
        name: caddy
      tags: caddy

- hosts: all
  become: true
  roles:
    - name: healthcheck
      import_role:
        name: healthcheck
      tags: healthcheck

- hosts:
    - gitcoin-js-ceramic-3.3boxlabs.com
    - gitcoin-go-ipfs-1.3boxlabs.com
  become: true
  roles:
    - name: migration
      import_role:
        name: migration
      tags: migration
    - name: healthcheck
      import_role:
        name: healthcheck
      tags: healthcheck

- hosts:
    - gitcoin-js-ceramic-4.3boxlabs.com
    - gitcoin-go-ipfs-2.3boxlabs.com
  become: true
  roles:
    - name: backup
      import_role:
        name: backup
      tags: backup
    - name: healthcheck
      import_role:
        name: healthcheck
      tags: healthcheck
