apiVersion: v1
kind: Service
metadata:
  name: {{ include "ceramic.fullname" . }}
  labels:
    {{- include "ceramic.labels" . | nindent 4 }}
spec:
  type: {{ .Values.composedb.service.type }}
  ports:
    - port: {{ .Values.composedb.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ceramic.selectorLabels" . | nindent 4 }}
