---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "ceramic.fullname" . }}-admin
  labels:
    {{- include "ceramic.labels" . | nindent 4 }}
data:
    private-key: {{ .Values.composedb.secret.privateKey | b64enc }}
    db-username: {{ .Values.postgresql.auth.username | b64enc }}
    db-password: {{ .Values.postgresql.auth.password | b64enc }}