apiVersion: v1
kind: Service
metadata:
  name: {{ include "ceramic.ipfs.fullname" . }}
  labels:
    {{- include "ceramic.ipfs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ipfs.service.type }}
  ports:
    - port: {{ .Values.ipfs.service.swarm.port }}
      targetPort: swarm
      protocol: TCP
      name: swarm
    - port: {{ .Values.ipfs.service.api.port }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.ipfs.service.gateway.port }}
      targetPort: gateway
      protocol: TCP
      name: gateway
    - port: {{ .Values.ipfs.service.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "ceramic.ipfs.selectorLabels" . | nindent 4 }}
