---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: optel
  namespace: optel
  labels:
    app: optel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: optel
  template:
    metadata:
      labels:
        app: optel
    spec:
      containers:
        - name: opentelemetry
          image: otel/opentelemetry-collector
          command:
            - /otelcol
            - --config=/config/optel-config.yaml
          ports:
            - containerPort: 4318
              name: optel-receiver
            - containerPort: 8889
              name: optel-exporter
          env:
            - name: PROMETHEUS_REMOTE_WRITE_URL
              valueFrom:
                secretKeyRef:
                  name: optel-secrets
                  key: PROMETHEUS_REMOTE_WRITE_URL
            - name: OPTEL_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CLUSTER_NAME
              valueFrom:
                secretKeyRef:
                  name: optel-secrets
                  key: CLUSTER_NAME
          resources:
            limits:
              cpu: 250m
              memory: 1Gi
              ephemeral-storage: 1Gi
            requests:
              cpu: 250m
              memory: 1Gi
              ephemeral-storage: 1Gi
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: optel-config
---
kind: Service
apiVersion: v1
metadata:
  name: optel
  namespace: optel
  labels:
    app: optel
spec:
  ports:
    - port: 4318
      targetPort: 4318
      protocol: TCP
      name: optel-receiver
    - port: 8889
      targetPort: 8889
      protocol: TCP
      name: optel-exporter
  selector:
    app: optel
  type: ClusterIP

