---
- name: Install caddy dependencies
  apt:
    pkg:
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
      - curl
    update_cache: yes

- name: Add caddy apt key
  apt_key:
    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
    keyring: /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    state: present

- name: Add caddy Repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"
    filename: caddy
    state: present

- name: Install caddy
  apt:
    pkg:
      - caddy
    update_cache: yes

- name: Template caddy config
  template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: root
    group: root
    mode: 0644
  register: caddy_config

- name: Start caddy
  systemd:
    name: caddy
    state: restarted
    enabled: yes
  when: caddy_config.changed
