---
namespace: ceramic

resources:
  - ./manifests/ipfs.yaml
  - ./manifests/composedb.yaml
  - ./manifests/postgres.yaml

configMapGenerator:
  - name: composedb-init
    files:
      - ./daemon-config.json
      - ./compose-init.sh
  - name: composedb-env
    envs:
      - ./composedb.env

images:
  - name: ceramicnetwork/composedb
    newName: ceramicnetwork/composedb
    newTag: dev
  - name: postgres/postgres
    newName: postgres
    newTag: 15-alpine
  - name: ipfs/ipfs
    newName: ceramicnetwork/go-ipfs-daemon@sha256
    newTag: 836f9832efde6d0c561dedb1529202eecb065c2bb85b5f04f29b0b72ba7f60ba