- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - jq
    - unzip
    - acl
    - rsync
    - postgresql-client

- name: create user
  ansible.builtin.user:
    name: ceramic
    state: present
    shell: /bin/bash
    home: /home/ceramic

- name: Format and mount js-ceramic block device
  block:
    - name: Create persistent data location
      community.general.filesystem:
        fstype: ext4
        dev: "{{ js_ceramic_data_block_path }}"

    - name: Mount persistent data location
      ansible.posix.mount:
        path: "{{ data_store_mount_path }}"
        src: "{{ data_store_mount_path }}"
        fstype: ext4
        state: mounted

    - name: Change ceramic disk owner to ceramic
      ansible.builtin.file:
        path: "{{ data_store_mount_path }}"
        state: directory
        owner: ceramic

    - name: Create js_ceramic_data for persistent data storage
      ansible.builtin.file:
        path: "{{ data_store_mount_path }}/"
        state: directory
        owner: ceramic

  when: js_ceramic_data_block_path is defined

- name: Format and mount rust-ceramic block device
  block:
    - name: Create persistent data location
      community.general.filesystem:
        fstype: ext4
        dev: "{{ rust_ceramic_data_block_path }}"

    - name: Mount persistent data location
      ansible.posix.mount:
        path: "{{ rust_ceramic_data_mount_path }}"
        src: "{{ rust_ceramic_data_block_path }}"
        fstype: ext4
        state: mounted

    - name: Create rust_ceramic_data for persistent data storage
      ansible.builtin.file:
        path: "{{ rust_ceramic_data_mount_path }}/rust_ceramic_data/"
        state: directory
        owner: ceramic
  when: rust_ceramic_data_block_path is defined
